### ISSUE TITLE
面包屑问题

### ISSUE THREAD

**Issue by ZGINMADAO** [tangtanglove/fullstack-backend#11]
你好,请教个问题。
![image](https://user-images.githubusercontent.com/17716544/64939270-0e1bb600-d893-11e9-98e3-db65ea6a25d4.png)
上面图是今天根据最新的代码搭建的 但是面包屑导航其实少了一个。

但是我看演示站是可以的
![image](https://user-images.githubusercontent.com/17716544/64939345-49b68000-d893-11e9-9c41-e424389b909d.png)

最开始我以为你演示站返回的接口中有 "编辑文章"的路由信息，但是我看了好像也没有 ，请问这块是怎么处理的  感谢！

**Comment by tangtanglove** [comment]
面包屑导航是根据前端的菜单生成的，可能有点儿小问题，等我看看
