### ISSUE TITLE
角色权限不生效

### ISSUE THREAD

**Issue by ninstein** [tangtanglove/fullstack-backend#13]
给新角色配置菜单权限提交后不生效，修改角色权限时上次提交内容没有被存储。
新角色的管理员帐号登陆后没有任何权限。

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/2425371/67923259-416a9800-fbe8-11e9-96e7-c7e56c70bc9f.png)
绑定权限后才能生效。
