### ISSUE TITLE
同步权限数据重复

### ISSUE THREAD

**Issue by ninstein** [tangtanglove/fullstack-backend#14]
多次点击权限列表-同步权限后，部分权限重复出现，如 api/admin/goodsOrder/afterSaleChangeStatus

**Comment by tangtanglove** [comment]
等我检查一下

**Comment by ninstein** [comment]
暂时用这段sql删除重复权限了：

DELETE permissions
FROM
 permissions, 
 (
  SELECT
   min(id) id,
   name,
   guard_name
  FROM
   permissions
  GROUP BY
   name,guard_name
  HAVING
   count(*) > 1
 ) t2
WHERE
 permissions.name = t2.name 
 and permissions.guard_name = t2.guard_name
AND permissions.id > t2.id;
