### ISSUE TITLE
安装成功后，进后台点击任何页面报错

### ISSUE THREAD

**Issue by winhave** [tangtanglove/fullstack-backend#3]
ErrorException: count(): Parameter must be an array or an object that implements Countable in file
执行composer update后，问题依然没得到解决，请指教！

**Comment by tangtanglove** [comment]
1.composer install试一下；
2.php7.1以上版本。

**Comment by winhave** [comment]
初始时，是通过composer install安装的；
目前：
Laravel Framework 5.8.23
PHP 7.2.5-1
网上搜索原因，说的是 count 只能 countable type 的变量
你的环境没遇到过这个问题吗？

**Comment by tangtanglove** [comment]
昨天晚上刚刚安装的，没有问题。

**Comment by winhave** [comment]
ErrorException: count(): Parameter must be an array or an object that implements Countable in file /home/vagrant/Code/app/Http/Controllers/Controller.php on line 55

**Comment by winhave** [comment]
我把５５行的这个 count 去掉就正常了；
另外还有个错误：GET http://fullstack.qasl.cn/api/auth_routes 404 (Not Found)
你的演示站也存在这个错误

**Comment by tangtanglove** [comment]
这个错误：GET http://fullstack.qasl.cn/api/auth_routes 404 (Not Found)
暂时先不用管，因为用的ant pro2.0有些废弃代码没有删除；现在正准备更新ant pro4.0。

**Comment by winhave** [comment]
55行改用：if( !empty($search) ) 
进行判断了
