### ISSUE TITLE
登录页面没有显示验证码

### ISSUE THREAD

**Issue by huahuasichun** [tangtanglove/fullstack-backend#6]
在登录账号的页面，登录账户名密码，但是没有显示验证码，点击登录按钮会提示验证码错误

**Comment by tangtanglove** [comment]
本地部署没有验证码吗？

**Comment by tangtanglove** [comment]
麻烦截图一下

**Comment by huahuasichun** [comment]
[image: 1.png]就是这种情况，登录页面显示的蚂蚁金服，是我没有安装好吗

tangtanglove <notifications@github.com> 于2019年7月31日周三 下午5:13写道：

**Comment by huahuasichun** [comment]
![1](https://user-images.githubusercontent.com/52898848/62260148-8ba27880-b443-11e9-9724-fd4a75ab3da1.png)

**Comment by tangtanglove** [comment]
额，新版本前端没有更新，我处理一下。

**Comment by tangtanglove** [comment]
可以了

**Comment by huahuasichun** [comment]
好的好的呢！
